### PR TITLE
Rmf updates

### PR DESCRIPTION
**Pull request by pallavipannu**
@deepio-oc this example is working fine till training stage, in serving it creates a prediction endpoint but the prediction is coming as undefined in webapp inference. I tried with both csv (test.csv (in sklearn branch ) and also the titanic_sample.csv in dkube-examples-internal branch. 

Attaching the screenshot
Screenshot from 2021-03-19 20-41-59

do we have to use some other test dataset for inference?

**README is completed, Please merge.**

### CODE REVIEW

**Review by larryc1200 — CHANGES_REQUESTED** [review]
- The dataset that you are pointing to is from the internal repo - everything should come from either our dkube-examples repo or some other original source
 - For the last IDE step, if we are going to have them create their own py files, we need to explain the differences necessary.  
 - The readme should also let them know that if they don't make any changes other than hyperparameters, they can use the ones that are already in that folder
 - In 2.2 you can't go right from a model to a deployment.  You need to publish first.  So there may be a step missing.  Our examples should work in 2.2, since that is the general release.
 - In the last step, it sends them to a pipeline file from a repo, but isn't the right pipeline file already in the folder?  They can just go to the IDE and run it, right?  If so, please specify anything that they need to do in order to have the PL work.
 - I haven't tried it - I assume that someone will try it out based on the steps as part of the QA.

**Comment by deepio-oc** [comment]
@pallavi-pannu-oc you should keep the sklearn-examples as repo name when someone creates code repo. The reason is if one is trying multiple branches from this repo, it will conflict if they are all named as dkube-examples

Secondly, serving should have worked. I believe I tested it. Could you investigate why it is not working ? test.csv in the branch is the right dataset to try.

**Comment by riteshkarval** [comment]
@pallavi-pannu-oc the prediction is showing undefined because the UI is checking for the **result** key. Can you change the response key from predictions to result in https://github.com/oneconvergence/dkube-examples/blob/rmf/titanic/transformer.py#L61

**Comment by deepio-oc** [comment]
@pallavi-pannu-oc we are using dataset from here for sklearn titanic

https://dkube.s3.amazonaws.com/datasets/titanic.zip

Lets not use any dataset from git URL in these examples.

**Pull request merged**
