### PR TITLE
Add sdk examples from dkube sdk repository

### PR DESCRIPTION
**Pull request by tijithomas**
fixes https://github.com/oneconvergence/gpuaas/issues/9072

### CODE REVIEW

**Comment by tijithomas** [comment]
@riteshkarvaloc Please review this. Also, if you think any of the other examples from Dkube SDK repo needs to be here, let me know.

**Comment by tijithomas** [comment]
1. 5-pipeline_sdk.ipynb - there is no example of pipeline using SDK, especially of the below kind:
      ```    training_name= generate('mnist')
    training = DkubeTraining(str(user), name=training_name, description='triggered from dkube pl launcher')
    training.update_container(framework="tensorflow_2.0.0", image_url="ocdr/dkube-datascience-tf-cpu:v2.0.0-10")
    training.update_startupscript('python model.py')
    training.add_code(str(code))
    training.add_input_dataset(str(dataset), mountpath='/opt/dkube/input')
    training.add_output_model(str(model), mountpath='/opt/dkube/output')

    training_op = dkube_training_op(
                name='mnist-training',
                authtoken=authtoken,
                training=training)```
3. 6-featureset.ipynb - There is no example of uploading featureset spec file for preprocessing.

**Comment by deepio-oc** [comment]
SDK based pipeline components is not officially supported and tested by QA. we should remove that example.  Featureset SDK api is covered under titanic example. We can enhance that by specifying YAML spec. remove comments and output from cell to keep the file sort and clean.

**Comment by tijithomas** [comment]
@deepio-oc I have removed the pipeline using sdk example.
For the featureset example,
The existing examples under titanic :
1. preprocess.py (https://github.com/oneconvergence/dkube-examples/blob/tensorflow/titanic/preprocess.py)
      input is csv (train and test)
      output is featureset
2. pipeline.ipynb - also utilizes preprocess.py

But in the example added from dkube sdk repository, featurespec file is uploaded and used in preprocessing to create a featureset as output (all done using sdk). Training and testing data approach is not utilised here. 

To enhance the example under titanic to use the yaml spec, we have to change preprocess.py, pipeline.ipynb and owner/resources.ipynb

**Comment by hemanthravi** [comment]
@deepio-oc 
Can we keep this example in addition to titanic to demonstrate the different SDK APIs. This will be in place of merging these to the titanic example, merging doesn't seem straight forward.

**Comment by deepio-oc** [comment]
@hemanthravi I discussed with @tijithomas. There is only 1 API which is additional in new notebook and it is simple to add that call in existing notebook.

**Comment by hemanthravi** [comment]
@deepio-oc 
Tiji showed me the example and it didn't look like the same APIs can be used in the titanic example. Could you check with her.

**Comment by deepio-oc** [comment]
@tijithomas  we do not need 2 spec yaml files. You can delete one. Also we dont need to upload spec for both feature sets. That way we show usage with and without spec yaml.

**Pull request merged**
