### PR TITLE
Add sdk examples (moved from sdk repo) and update tensorflow images

### PR DESCRIPTION
**Pull request by tijithomas**
Fixes https://github.com/oneconvergence/gpuaas/issues/9072

### CODE REVIEW

**Comment by deepio-oc** [comment]
@tijithomas do not create new branches in dkube-examples unless required. You can fork dkube-examples, make changes and create PR here. We should be able to distribute missing SDK examples to one of the existing branches.

Also , can we go through the list of examples you identified are missing. We should be careful of what we are adding here because we need to maintain them going forward.

**Comment by tijithomas** [comment]
@deepio-oc This branch is only for this PR and will be deleted after merge.
This PR is work in progress. As a first step, I have only moved the files to this repo, and made sure it works with the updated tensorflow images. Except for the below files, rest would be deleted:
1. demo.py (contains creation of Jupyterlab/Rstudio notebooks, and other examples of sdk)  
2. featureset examples using sdk 
3. mlflow_reporting.py

**Comment by deepio-oc** [comment]
irrespective of the purpose, we shouldnt create temp branches. this is customer facing repo and the README files are written assuming certain branches in mind. 

we can discuss 1,2,3 tomorrow.

**Comment by tijithomas** [comment]
@deepio-oc I understand. I will delete this branch.

**Pull request closed without merging**
