### PR TITLE
cleaning training repo

### PR DESCRIPTION
**Pull request by riteshkarval**

### CODE REVIEW

**Comment by hemanthravi** [comment]
Why are these files deleted?
This example was working.

**Comment by riteshkarval** [comment]
The example is not tested end-to-end also it's missing Katib support. 

It would required some efforts to make it working end-to-end.

**Comment by hemanthravi** [comment]
We used the example end-end for Altos demo. It was working.

**Comment by riteshkarval** [comment]
MLFlow training would work, but Katib and monitoring is incomplete in chest-xray example. 

Did we used other branch or the same training branch for Altos demo?

**Comment by songole** [comment]
The branch has been renamed. The paths have changed. Other than that it
should work.
Creation of monitor is from UI. Datagen should work.

**Pull request closed without merging**
